_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 6
                - 53
                - 55
            "3":
                - 23
                - 24
                - 55
            "4": 3.10.12
            "5": 0.19.4
            "8":
                - 1
                - 5
            "12": 0.19.4
            "13": linux-x86_64
n_estimators:
    value: 100
